# server:
#     port: 8084

# spring:
#     datasource:
#         # url: jdbc:postgresql://localhost:5432/test
#         url: jdbc:postgresql://db:5432/test
#         username: postgres
#         password: Huyhoangdeptrai2003@
#         driver-class-name: org.postgresql.Driver
#     jpa:
#         hibernate:
#             ddl-auto: create-drop
#         show-sql: true
#         database: postgresql
#         database-platform: org.hibernate.dialect.PostgreSQLDialect

 